# list of unsupervised losses:
# - "pca_singleview"
# - "pca_multiview"
# - "temporal"
# - "unimodal_mse"
# - "unimodal_wasserstein"
# - null: if null, assume a model is supervised.
losses_to_use: [temporal]

# whether to learn the weights for the unsupervised losses
learn_weights: False

# reach parameter for wasserstein loss
reach: None

# resnet version for backbone: resnet18 | resnet34 | resnet50 | resnet01 | resnet152
# efficientnet version for backbone eff0 | eff1 | eff2
backbone: "eff0"

# prediction mode: "heatmap" | "regression"
model_type: "heatmap"

# which heatmap loss to use: "mse" | "wasserstein"
heatmap_loss_type: "mse"

# directory name for model saving
model_name: "my_base_toy_model"
